# Generated by Django 4.0.5 on 2022-07-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('data', models.JSONField(verbose_name='Данные ошибки')),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Ошибки',
                'ordering': ['-timestamp'],
            },
        ),
    ]
