# Generated by Django 4.0.5 on 2022-07-21 04:12

from django.db import migrations, models
import django.db.models.deletion
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(db_index=True, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', models.JSONField(default=scraping.models.default_urls, verbose_name='Данные URL')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urls_city', to='scraping.city', verbose_name='Город')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urls_lang', to='scraping.language', verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'unique_together': {('city', 'language')},
            },
        ),
    ]
